config/routes.rb
UMBook::Application.routes.draw do
  resources :post_comments

  resources :posts

  resources :photos

  resources :albums

  devise_for :users

  resources :users do
    get :search, on: :collection
  end

  get 'pages/home'

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match "/friendships(.:format)", to: "friendships#create", via: :post, as: 'friendships'
  match "/friendships/:id(.:format)", to: "friendships#update", via: :put
  match "/friendships/:id(.:format)", to: "friendships#destroy", via: :delete
end

app/models/user.rb
class User < ActiveRecord::Base
  image_accessor :profile_picture
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
    :name, :lastname, :sex, :born_date, :profile_picture, :retained_profile_picture, :remove_profile_picture
  # attr_accessible :title, :body
  
  has_many :albums
  has_many :photo_comments
  has_many :post_comments
  has_many :sended_posts, foreign_key: 'from_user_id', class_name: 'Post'
  has_many :received_posts, foreign_key: 'to_user_id', class_name: 'Post'
  has_many :sended_invites, foreign_key: 'user1_id', class_name: 'Friendship'
  has_many :received_invites, foreign_key: 'user2_id', class_name: 'Friendship'

  def posts
    Post.where("from_user_id = ? OR to_user_id = ?",id,id).order("updated_at DESC")
  end

  def all_posts
    all_posts = posts
    friends.each do |friend|
      all_posts.concat friend.posts
    end
    all_posts.uniq{|p| p.id }.sort_by{|p| p.updated_at}.reverse
  end

  def friends
    friends = sended_invites.where(status: true).map { |si| si.to_user }
    friends.concat received_invites.where(status: true).map { |ri| ri.from_user }
  end

  def invite_pending?(user)
    received_invites.where(user1_id: user, status: false).exists? || sended_invites.where(user2_id: user, status: false).exists?
  end

  def friend_of?(user)
    received_invites.where(user1_id: user, status: true).exists? || sended_invites.where(user2_id: user, status: true).exists? || (user.id == id)
  end

  def invite_to?(user)
    sended_invites.where(user2_id: user).exists?
  end

  def friendship_id(user)
    ri = received_invites.where(user1_id: user).first
    si = sended_invites.where(user2_id: user).first
    if ri
      friendship_id = ri.id
    elsif si
      friendship_id = si.id
    end
    friendship_id  
  end

  def self.find_by_name_or_lastname(query, id)
    query += "%"
    where("id != ? AND (name ILIKE ? or lastname ILIKE ? OR (name || ' ' ||lastname) ILIKE ?)",id,query,query,query)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
  load_and_authorize_resource

  def edit
  end
  
  def show
    @idUsuario = params[:id]
  end

  def search
    @users = User.find_by_name_or_lastname(params[:q], current_user.id)
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    redirect_to :back
  end

  def destroy
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name(user, link = false)
    full_name = "#{user.name} #{user.lastname}"
    if link
      full_name = link_to(full_name, user)
    end
    full_name
  end

  def user_picture(user, size)
    return user.profile_picture.thumb(size).url if user.profile_picture
    "rails.png"
  end

  def invite_message(user)
  end
end

app/views/users/edit.html.erb
<br>
<%= simple_form_for @user do |f|%>
<div class="row-fluid">
  <div class="span2">
    <%= image_tag user_picture(current_user, "200x200"), class: 'img-polaroid' %>
  </div>
  <div class="span10"> 
    <h2><%= f.input :name, input_html: {class: "input-xlarge"}, label: false %></h2>
    <h2><%= f.input :lastname, input_html: {class: "input-xlarge"}, label: false %></h2>

    <%= f.file_field :profile_picture %>
    <%= f.hidden_field :retained_profile_picture %>
    <%= f.check_box :remove_profile_picture %>

  </div>

</div>
<div class="row-fluid">
  <br>
  <h4>Sexo: </h4><%= f.input :sex, input_html: {class: 'input-xlarge'}, label: false %>
<h4>Fecha de Nacimiento: </h4><%= f.input :born_date, input_html: {class: 'input-xlarge'}, label: false %>
  <br><br>
  <%= f.submit 'Guardar', class: 'btn' %>
</div><!--/row-->
<% end %>
<hr>

app/views/users/search.html.erb
<div class="hero-unit">
  <h1>UM BooK, Red Social</h1>
</div>
<h3>Resultados para la Busqueda</h3><br>
<div class="row-fluid">
  <% @users.each do |user| %>
    <div class="row-fluid">
      <div class="span1"> 
      </div>
      <div class="span1">
        <%= image_tag user_picture(user, "60x60"), class: 'img-rounded' %>
      </div>
      <div class="span5"> 
        <%= full_name user, true %>
      </div>
      <div class="span5"> 
        <% if !current_user.friend_of? user %>
          <% if current_user.invite_pending? user %>
            <% if current_user.invite_to? user %>
              Esperando confirmacion
            <% else %>
              <%= simple_form_for :friendship, url: '/friendships/' + current_user.friendship_id(user).to_s, method: 'put' do |f| %>
                <%= f.input :friendship_id, as: :hidden, input_html: {value: current_user.friendship_id(user) } %>
                <%= f.submit 'Aceptar amistad', class: 'btn' %>
              <% end %>
            <% end %>
          <% else %>
            <%= simple_form_for :friendship, url: friendships_path do |f| %>
              <%= f.input :user2_id, as: :hidden, input_html: {value: user.id} %>
              <%= f.submit 'Agregar a mis amigos', class: 'btn' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>  
    <br>
  <% end %>
</div><!--/row-->
<hr>

app/views/users/show.html.erb
<br>
<div class="row-fluid">
  <div class="span2">
    <%= image_tag user_picture(@user,"200x200"), class: 'img-polaroid' %>
  </div>
  <div class="span10"> 
    <h2><%= full_name @user %></h2> 
    <br>
    <% if !current_user.friend_of? @user %>
      <% if current_user.invite_pending? @user %>
        <% if current_user.invite_to? @user %>
          Esperando confirmacion
        <% else %>
          <%= simple_form_for :friendship, url: '/friendships/' + current_user.friendship_id(@user).to_s, method: 'put' do |f| %>
            <%= f.input :friendship_id, as: :hidden, input_html: {value: current_user.friendship_id(@user) } %>
            <%= f.submit 'Aceptar amistad', class: 'btn' %>
          <% end %>
        <% end %>
      <% else %>
        <%= simple_form_for :friendship, url: friendships_path do |f| %>
          <%= f.input :user2_id, as: :hidden, input_html: {value: @user.id} %>
          <%= f.submit 'Agregar a mis amigos', class: 'btn' %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="notice"><%= notice %></div>
<% if can?(:create, Post) and current_user.friend_of?(@user) %>
  <div class="row-fluid">
    <br>
    <p><img src="/assets/umbook_paper.png" class="img-rounded" height="20" width="20"> Escribir a <%= full_name @user %><p/>
    <p>
    <%= simple_form_for :post, url: posts_path do |f| %>
      <%= f.input :content, as: :text, label: false, input_html: {class: 'post_text_area field span12', rows: '1', placeholder: '¿Qué estás pensando?'} %>
      <%= f.input :to_user_id, as: :hidden, input_html: {value: @user.id} %>
      <%= f.submit 'Postear', class: 'btn' %>
    <% end %>
    </p>
    <br>
  </div><!--/row-->
<% end %>
<% @user.posts.each do |post| %>
  <% if can? :read, post %>
    <div class="row-fluid">
      <div class="row-fluid">
        <div class="span1">
          <%= image_tag user_picture(post.from_user,"50x50"), class: 'img-rounded' %>
        </div>
        <div class="span11">
          <% if post.from_user == post.to_user %>
            <%= full_name post.from_user, true %> Dice:<br />
          <% else %>
            <%= full_name post.from_user, true %> >> <%= full_name post.to_user, true %><br />
          <% end %>
          <%= post.content %>
        </div>
      </div>
      <br>
      <div class="row-fluid">
        <div class="span1"></div>
        <div class="span11">
          <%= simple_form_for :post_comment, url: post_comments_path do |f| %>
            <%= f.input :content, as: :text, label: false, input_html: {class: 'post_comment_text_area', rows: '3', placeholder: 'Escribe un comentario'} %>
            <%= f.input :post_id, as: :hidden, input_html: {value: post.id} %>
            <%= f.submit 'Comentar', class: 'btn' %>
          <% end %>
        </div>
      </div>
      <% post.post_comments.order("updated_at DESC").each do |post_comment| %> 
        <% if can? :read, post_comment %>
          <div class="row-fluid">
            <div class="span1">
            </div>
            <div class="span11">
              <div class="span12">
                <div class="span1">
                  <%= image_tag user_picture(post_comment.user,"30x30"), class: 'img-rounded' %>
                </div>
                <div class="span11">
                  <%= full_name post_comment.user %> Dice:<br />
                  <%= post_comment.content %>
                </div>
              </div>
            </div>
          </div><!--/span-->
          <br>
        <% end %>
      <% end %>
    </div><!--/row-->
    <hr>
  <% end %>
<% end %>