config/routes.rb
UMBook::Application.routes.draw do
  resources :post_comments

  resources :posts

  resources :photos

  resources :albums

  devise_for :users

  resources :users do
    get :search, on: :collection
  end

  get 'pages/home'

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match "/friendships(.:format)", to: "friendships#create", via: :post, as: 'friendships'
  match "/friendships/:id(.:format)", to: "friendships#update", via: :put
  match "/friendships/:id(.:format)", to: "friendships#destroy", via: :delete
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  attr_accessible :description, :name
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  load_and_authorize_resource

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])
    @album.user = current_user
    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Nombre' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Descripcion' %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editar album</h1>

<%= render 'form' %>

<%= link_to 'Ver Album', @album %> |
<%= link_to 'Volver', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= album.description %></td>
    <td><%= album.user %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<br>
<div class="row-fluid">
  <div class="span2">
    <%= image_tag user_picture(@album.user, "200x200"), class: 'img-polaroid' %>
  </div>
  <div class="span10"> 
    <h2><%= full_name @album.user %></h2> 
    <br>
  </div>
</div>
<div class="row-fluid">
  <br>
  <h3>Album: <%= @album.name %></h3>
  <h4>Descripcion: <%= @album.description %></h4>
  <%= link_to 'Editar Album', edit_album_path(@album), class: 'btn' if can? :update, @album %>
  <%= link_to 'Subir fotos', new_photo_path(album: @album.id), class: 'btn' if can?(:create, Photo) and @album.user == current_user %>
</div><!--/row-->
<hr>
<p>
<button id="start-slideshow" class="btn btn-large btn-success" data-slideshow="5000" data-target="#modal-gallery" data-selector="#gallery [data-gallery=gallery]">Iniciar presentacion</button>
</p>
<div id="gallery" data-toggle="modal-gallery" data-target="#modal-gallery">
  <% @album.photos.each do |photo| %>
    <% if can? :read, photo %>
      <% if photo.image %>
        <%= link_to(image_tag(photo.image.thumb("100x100").url), photo.image.url, title: photo.description, data: {gallery: 'gallery'}) %>
      <% end %>
    <% end %>
  <% end %>
</div>
<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade" tabindex="-1">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3 class="modal-title"></h3>
  </div>
  <div class="modal-body"><div class="modal-image"></div></div>
  <div class="modal-footer">
    <a class="btn modal-download" target="_blank">
      <i class="icon-download"></i>
      <span>Download</span>
    </a>
    <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000">
      <i class="icon-play icon-white"></i>
      <span>Slideshow</span>
    </a>
    <a class="btn btn-info modal-prev">
      <i class="icon-arrow-left icon-white"></i>
      <span>Previous</span>
    </a>
    <a class="btn btn-primary modal-next">
      <span>Next</span>
      <i class="icon-arrow-right icon-white"></i>
    </a>
  </div>
</div>

<br />