config/routes.rb
UMBook::Application.routes.draw do
  resources :post_comments

  resources :posts

  resources :photos

  resources :albums

  devise_for :users

  resources :users do
    get :search, on: :collection
  end

  get 'pages/home'

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match "/friendships(.:format)", to: "friendships#create", via: :post, as: 'friendships'
  match "/friendships/:id(.:format)", to: "friendships#update", via: :put
  match "/friendships/:id(.:format)", to: "friendships#destroy", via: :delete
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UMBook</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% @user ||= current_user %>
    <div class="navbar navbar-static-top navbar-inverse">
      <div class="navbar-inner">
        <div class="row-fluid">
          <div class="span2">

            <a class="brand" href="#"><img style="width: 30px;height: 30px;" src="/assets/gubu.svg" />UMBook</a>


          </div>
          <div class="span7">
            <%= form_tag search_users_path, class: 'navbar-search input-block-level', method: 'get' do %>
              <%= text_field_tag :q, nil, class: 'search-query input-block-level', placeholder: 'Buscar' %>
            <% end %>

          </div>
          <div class="span3">
            <ul class="nav pull-right">
              <li <%= "class=active" if controller_name == 'pages' %>><%= link_to 'Inicio', pages_home_path %></li>
              <li <%= "class=active" if controller_name == 'users' %>><%= link_to 'Perfil', user_path(current_user) %></li>
              <li id="fat-menu" class="dropdown">
              <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-cog icon-white"></i><b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
              </ul>
              </li>

            </ul>

          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <%= yield :left_bar %>
          <% unless content_for? :left_bar %>
            <div class="well sidebar-nav">

              <ul class="nav nav-list">
                <li class="nav-header"><p>Perfil <%= link_to 'Editar', edit_user_path(current_user) if can? :update, @user %></p></li>
                <li class=""><%= full_name @user, true %></li>
                <%= image_tag user_picture(@user,"50x50"), class: 'img-rounded' %>
              </ul>
            </div><!--/.well -->
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header">Albums</li>
                <% @user.albums.each do |album| %>
                  <% if can? :read, album %>
                    <li><%= link_to album.name, album %></li>
                  <% end %>
                <% end %>
              </ul>
            </div><!--/.well -->
          <% end %>
        </div><!--/span-->
        <div class="span8">
          <%= yield %>
        </div><!--/span-->
        <div class="span2">
          <%= yield :right_bar %>
          <% unless content_for? :right_bar %>
            <div class="well sidebar-nav">
              <ul class="nav nav-list">
                <li class="nav-header">Amigos / Contactos</li>
                <% @user.friends.each do |friend| %>
                  <li><%= image_tag user_picture(friend,"42x42"), class: 'img-rounded'%><%= link_to full_name friend, true %></li>
                <% end %>
              </ul>

            </div><!--/.well -->

          <% end %>
        </div><!--/span-->
      </div><!--/row-->
      <hr>
      <footer>
      <p> UM Book Todos los Derechos Reservados por el tal Sukerberg aqui seran violao's</p>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UMBook</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="navbar navbar-static-top navbar-inverse">
      <div class="navbar-inner">
        <a class="brand" href="#"><img style="width: 30px;height: 30px;" src="/assets/gubu.svg" />UMBook</a>
        <%= form_for("user", :url => user_session_path, html: {class: 'navbar-form pull-right'}) do |f| %>
          <%= f.text_field :email, placeholder: 'Email' %>
          <%= f.password_field :password, placeholder: 'Password' %>
          <%= f.submit 'Entrar' %>
          <br />
          <%= f.check_box :remember_me %> No cerrar sesi&oacute;n
          <%# link_to "¿Olvidaste la contraseña?", new_password_path('user') %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>